"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.University = exports.Temple = exports.SdiDefence = exports.RecyclingCenter = exports.PowerPlant = exports.Palace = exports.NuclearPlant = exports.MassTransit = exports.Marketplace = exports.ManufacturingPlant = exports.Library = exports.HydroPlant = exports.Granary = exports.Factory = exports.Courthouse = exports.Colosseum = exports.CityWalls = exports.Cathedral = exports.Barracks = exports.Bank = exports.Aqueduct = void 0;
var CityImprovements_1 = require("@civ-clone/library-city/CityImprovements");
Object.defineProperty(exports, "Aqueduct", { enumerable: true, get: function () { return CityImprovements_1.Aqueduct; } });
Object.defineProperty(exports, "Bank", { enumerable: true, get: function () { return CityImprovements_1.Bank; } });
Object.defineProperty(exports, "Barracks", { enumerable: true, get: function () { return CityImprovements_1.Barracks; } });
Object.defineProperty(exports, "Cathedral", { enumerable: true, get: function () { return CityImprovements_1.Cathedral; } });
Object.defineProperty(exports, "CityWalls", { enumerable: true, get: function () { return CityImprovements_1.CityWalls; } });
Object.defineProperty(exports, "Colosseum", { enumerable: true, get: function () { return CityImprovements_1.Colosseum; } });
Object.defineProperty(exports, "Courthouse", { enumerable: true, get: function () { return CityImprovements_1.Courthouse; } });
Object.defineProperty(exports, "Factory", { enumerable: true, get: function () { return CityImprovements_1.Factory; } });
Object.defineProperty(exports, "Granary", { enumerable: true, get: function () { return CityImprovements_1.Granary; } });
Object.defineProperty(exports, "HydroPlant", { enumerable: true, get: function () { return CityImprovements_1.HydroPlant; } });
Object.defineProperty(exports, "Library", { enumerable: true, get: function () { return CityImprovements_1.Library; } });
Object.defineProperty(exports, "ManufacturingPlant", { enumerable: true, get: function () { return CityImprovements_1.ManufacturingPlant; } });
Object.defineProperty(exports, "Marketplace", { enumerable: true, get: function () { return CityImprovements_1.Marketplace; } });
Object.defineProperty(exports, "MassTransit", { enumerable: true, get: function () { return CityImprovements_1.MassTransit; } });
Object.defineProperty(exports, "NuclearPlant", { enumerable: true, get: function () { return CityImprovements_1.NuclearPlant; } });
Object.defineProperty(exports, "Palace", { enumerable: true, get: function () { return CityImprovements_1.Palace; } });
Object.defineProperty(exports, "PowerPlant", { enumerable: true, get: function () { return CityImprovements_1.PowerPlant; } });
Object.defineProperty(exports, "RecyclingCenter", { enumerable: true, get: function () { return CityImprovements_1.RecyclingCenter; } });
Object.defineProperty(exports, "SdiDefence", { enumerable: true, get: function () { return CityImprovements_1.SdiDefence; } });
Object.defineProperty(exports, "Temple", { enumerable: true, get: function () { return CityImprovements_1.Temple; } });
Object.defineProperty(exports, "University", { enumerable: true, get: function () { return CityImprovements_1.University; } });
//# sourceMappingURL=CityImprovements.js.map