"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Temple = exports.Palace = exports.Marketplace = exports.Library = exports.Granary = exports.Courthouse = exports.Colosseum = exports.CityWalls = exports.Barracks = exports.Aqueduct = void 0;
var Aqueduct_1 = require("@civ-clone/base-city-improvement-aqueduct/Aqueduct");
Object.defineProperty(exports, "Aqueduct", { enumerable: true, get: function () { return Aqueduct_1.Aqueduct; } });
var Barracks_1 = require("@civ-clone/base-city-improvement-barracks/Barracks");
Object.defineProperty(exports, "Barracks", { enumerable: true, get: function () { return Barracks_1.Barracks; } });
var CityWalls_1 = require("@civ-clone/base-city-improvement-citywalls/CityWalls");
Object.defineProperty(exports, "CityWalls", { enumerable: true, get: function () { return CityWalls_1.CityWalls; } });
var Colosseum_1 = require("@civ-clone/base-city-improvement-colosseum/Colosseum");
Object.defineProperty(exports, "Colosseum", { enumerable: true, get: function () { return Colosseum_1.Colosseum; } });
var Courthouse_1 = require("@civ-clone/base-city-improvement-courthouse/Courthouse");
Object.defineProperty(exports, "Courthouse", { enumerable: true, get: function () { return Courthouse_1.Courthouse; } });
var Granary_1 = require("@civ-clone/base-city-improvement-granary/Granary");
Object.defineProperty(exports, "Granary", { enumerable: true, get: function () { return Granary_1.Granary; } });
var Library_1 = require("@civ-clone/base-city-improvement-library/Library");
Object.defineProperty(exports, "Library", { enumerable: true, get: function () { return Library_1.Library; } });
var Marketplace_1 = require("@civ-clone/base-city-improvement-marketplace/Marketplace");
Object.defineProperty(exports, "Marketplace", { enumerable: true, get: function () { return Marketplace_1.Marketplace; } });
var Palace_1 = require("@civ-clone/base-city-improvement-palace/Palace");
Object.defineProperty(exports, "Palace", { enumerable: true, get: function () { return Palace_1.Palace; } });
var Temple_1 = require("@civ-clone/base-city-improvement-temple/Temple");
Object.defineProperty(exports, "Temple", { enumerable: true, get: function () { return Temple_1.Temple; } });
//# sourceMappingURL=CityImprovements.js.map